# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI for Java

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        java: [8, 11]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn clean install -e -B -V -nsu --no-transfer-progress -P run-its -Dfailsafe-integration-test-port=8083

      - name: Upload artifact surefire-its
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: ${{ matrix.os }}-surefire-its
          path: |
            surefire-its/target/*/log.txt
            surefire-its/target/**/surefire-reports/*
            surefire-its/target/**/failsafe-reports/*
            !surefire-its/target/*-1617
            !surefire-its/target/failsafe-reports
